
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

api:
  insecure: true
  dashboard: true

log:
  level: "DEBUG"

accessLog:
  format: json

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  myresolver:
    acme:
      email: "tu-email@dominio.com"
      storage: "/etc/traefik/acme.json"
      httpChallenge:
        entryPoint: web

http:
  routers:
    # Router para nginx
    nginx-router:
      rule: "Host(`nginx.localhost`)"
      entryPoints:
        - "web"
      service: "nginx-service"
      middlewares:
        - "nginx-ratelimit"
      tls: # Si decides usar TLS
        certResolver: "myresolver" # Si tienes un certificado Let's Encrypt configurado, por ejemplo.

    # Router para la API
    api-router:
      rule: "Host(`api.localhost`) && PathPrefix(`/api`)"
      entryPoints:
        - "web"
      service: "api-service"
      middlewares:
        - "auth"
      tls: # Si decides usar TLS
        certResolver: "myresolver"

  services:
    nginx-service:
      loadBalancer:
        servers:
          - url: "http://nginx:80"

    api-service:
      loadBalancer:
        servers:
          - url: "http://api:80"

  middlewares:
    # Middleware para limitaci칩n de tasa en nginx
    nginx-ratelimit:
      rateLimit:
        average: 2
        burst: 1
        sourceCriterion:
          ipStrategy:
            depth: 1

    # Middleware para autenticaci칩n b치sica
    auth:
      basicAuth:
        users:
          - "test:$$apr1$$H6uskkkW$$IgXLP6ewTrSuBkTrqE8wj/"
          - "test2:$$apr1$$d9hr9HBB$$4HxwgUir3HP4EsggP/QNo0"

# Configuraci칩n del panel de control de Traefik
api:
  dashboard: true
  insecure: true
  # Si necesitas habilitar un puerto separado para el dashboard
  # entryPoints:
  #   - "web"
