global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":80"

api:
  insecure: true
  dashboard: true

log:
  level: "DEBUG"

accessLog:
  format: json

providers:
  docker:
    exposedByDefault: false

# Redireccionar tráfico hacia HTTPS (opcional si usas TLS)
# entryPoints:
#   web-secure:
#     address: ":443"
#   web:
#     address: ":80"
#     http:
#       redirections:
#         entryPoint:
#           to: web-secure
#           scheme: https
#           permanent: true

# Configuración para tus servicios
http:
  routers:
    # Router para un servicio de ejemplo
    my-service:
      rule: "Host(`example.com`)"
      entryPoints:
        - "web"
      service: "my-service"
      middlewares:
        - "example-middleware"
      tls: # Solo si quieres habilitar HTTPS
        certResolver: "myresolver" # Aquí definirías tu resolución de certificados

  services:
    my-service:
      loadBalancer:
        servers:
          - url: "http://my-container:8080"

  middlewares:
    # Middleware para redireccionar tráfico a HTTPS (si decides usar TLS)
    example-middleware:
      redirectScheme:
        scheme: https
        permanent: true

# Configuración del panel de control de Traefik
api:
  dashboard: true
  insecure: true
  # Si necesitas habilitar un puerto separado para el dashboard
  # entryPoints:
  #   - "web"

